version: '3.8'  

networks:
  backend:
  frontend:
   
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000
    deploy:
      replicas: 2
      restart_policy:
        condition: always
    networks:
      - frontend
    volumes:
      - .:/src/app
  
  nginx:
    image: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web    
    networks:
      - frontend

volumes:
  postgres_data: