version: '3.8'  

networks:
  backend:
  frontend:
   
services:
  web:
    build:
      context: ./student-management
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend
    volumes:
      - ./student-management:/src/app

volumes:
  postgres_data: