apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    events {
        worker_connections 1000;
    }

    http {
        upstream web-backend {
            server {{ include "helm-web.fullname" . }}-web:3000;
        }

        server {
            listen 80;
            location / {
                proxy_pass http://web-backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
