apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-container
        image: "{{ .Values.image.web.registry }}/{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
        imagePullPolicy: {{ .Values.image.web.pullPolicy }}
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-volume
          mountPath: /src/app
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: app-volume
        hostPath:
          path: /src/app

