apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    events {
        worker_connections 1000;
    }

    http {
        upstream all {
            server web:3000;
        }

        server {
            listen 80;
            location / {
                proxy_pass http://all;
            }
        }
    }
